;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        indent-for-tab-command
        org-delete-char
        org-self-insert-command
        wdired--self-insert
        ))

(setq mc/cmds-to-run-once
      '(
        eval-buffer
        edit/multiple-cursors-keymap/mc/edit-lines-and-exit
        edit/multiple-cursors-keymap/mc/mark-all-like-this-and-exit
        edit/multiple-cursors-keymap/mc/mark-next-like-this
        edit/multiple-cursors-keymap/mc/skip-to-next-like-this
        ))
