;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        c-electric-slash
        counsel-yank-pop
        downcase-region
        kill-visual-line
        mark-word
        mc:hydra-keymap/body
        org-beginning-of-line
        org-cycle
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-self-insert-command
        org-table-eval-formula
        paredit-doublequote
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-semicolon
        upcase-region
        wdired-finish-edit
        wgrep-finish-edit
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        mc:hydra-keymap/mc/edit-lines-and-exit
        mc:hydra-keymap/mc/mark-all-like-this-and-exit
        mc:hydra-keymap/mc/mark-next-like-this
        mc:hydra-keymap/mc/skip-to-next-like-this
        mc:hydra-keymap/mc/unmark-next-like-this
        ))
