;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		indent-for-tab-command
		mc/hydra-keymap/mc/mark-next-like-this
		))

(setq mc/cmds-to-run-once
      '(
		mc/hydra-keymap/mc/edit-lines-and-exit
		mc/hydra-keymap/mc/mark-all-like-this-and-exit
		))
